import { create } from "zustand";
import { AsyncStorage } from "@react-native-async-storage/async-storage";

type Language = "en" | "ar";

interface LanguageState {
  lang: Language;
  isRTL: boolean;
  setLang: (lang: Language) => void;
  toggleLang: () => void;
}

// Simple translations
const translations: Record<Language, Record<string, string>> = {
  en: {
    home: "Home",
    leads: "Leads",
    clients: "Clients",
    chat: "Chat",
    admin: "Admin",
    signIn: "Sign In",
    signUp: "Sign Up",
    signOut: "Sign Out",
    email: "Email",
    password: "Password",
    name: "Name",
    phone: "Phone",
    project: "Project",
    status: "Status",
    notes: "Notes",
    create: "Create",
    update: "Update",
    delete: "Delete",
    cancel: "Cancel",
    confirm: "Confirm",
    save: "Save",
    loading: "Loading...",
    noData: "No data",
    search: "Search...",
    filter: "Filter",
    all: "All",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    new: "New",
    inProgress: "In Progress",
    followUp: "Follow Up",
    interested: "Interested",
    notInterested: "Not Interested",
    sold: "Sold",
    welcome: "Welcome",
    dashboard: "Dashboard",
    recentActivity: "Recent Activity",
    myClients: "My Clients",
    myLeads: "My Leads",
    totalUsers: "Total Users",
    pendingUsers: "Pending Users",
    manageUsers: "Manage Users",
    approvals: "Approvals",
    auditLogs: "Audit Logs",
    permissions: "Permissions",
    createLead: "Create Lead",
    createClient: "Create Client",
    leadDetails: "Lead Details",
    clientDetails: "Client Details",
    updateStatus: "Update Status",
    activityHistory: "Activity History",
    lockClient: "Lock / Start Working",
    unlockClient: "Unlock",
    addFeedback: "Add Feedback",
    accountPending: "Account Pending",
    accountRejected: "Account Rejected",
    hello: "Hello",
    salesOverview: "Sales Activity Overview",
  },
  ar: {
    home: "الرئيسية",
    leads: "العملاء المحتملين",
    clients: "العملاء",
    chat: " المحادثة",
    admin: "الإدارة",
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    signOut: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    name: "الاسم",
    phone: "الهاتف",
    project: "المشروع",
    status: "الحالة",
    notes: "ملاحظات",
    create: "إنشاء",
    update: "تحديث",
    delete: "حذف",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    loading: "جار التحميل...",
    noData: "لا توجد بيانات",
    search: "بحث...",
    filter: "تصفية",
    all: "الكل",
    pending: "قيد الانتظار",
    approved: "موافق عليه",
    rejected: "مرفوض",
    new: "جديد",
    inProgress: "قيد العمل",
    followUp: "متابعة",
    interested: "مهتم",
    notInterested: "غير مهتم",
    sold: "تم البيع",
    welcome: "مرحباً",
    dashboard: "لوحة التحكم",
    recentActivity: "النشاط الأخير",
    myClients: "عملائي",
    myLeads: "عملائي المحتملين",
    totalUsers: "إجمالي المستخدمين",
    pendingUsers: "المستخدمين قيد الانتظار",
    manageUsers: "إدارة المستخدمين",
    approvals: "الموافقات",
    auditLogs: "سجل التدقيق",
    permissions: "الصلاحيات",
    createLead: "إنشاء عميل محتمل",
    createClient: "إنشاء عميل",
    leadDetails: "تفاصيل العميل المحتمل",
    clientDetails: "تفاصيل العميل",
    updateStatus: "تحديث الحالة",
    activityHistory: "سجل النشاط",
    lockClient: "قفل / بدء العمل",
    unlockClient: "إلغاء القفل",
    addFeedback: "إضافة تقييم",
    accountPending: "الحساب قيد الانتظار",
    accountRejected: "تم رفض الحساب",
    hello: "مرحباً",
    salesOverview: "نظرة عامة على نشاط المبيعات",
  },
};

export const useLang = create<LanguageState>((set, get) => ({
  lang: "ar",
  isRTL: true,
  setLang: (lang) => set({ lang, isRTL: lang === "ar" }),
  toggleLang: () => {
    const newLang = get().lang === "en" ? "ar" : "en";
    set({ lang: newLang, isRTL: newLang === "ar" });
  },
}));

export function t(key: string): string {
  const lang = useLang.getState().lang;
  return translations[lang][key] || key;
}
